# Generated by Django 4.2.8 on 2023-12-11 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_alter_task_options_alter_task_daily_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(default='missed_title', max_length=255),
            preserve_default=False,
        ),
    ]
