# Generated by Django 4.2.8 on 2023-12-11 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_task_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='daily',
        ),
        migrations.DeleteModel(
            name='Daily',
        ),
    ]
