# Generated by Django 4.2.8 on 2023-12-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_alter_task_due_date_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='https://static.vecteezy.com/system/resources/thumbnails/009/734/564/small/default-avatar-profile-icon-of-social-media-user-vector.jpg', upload_to='user_images'),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(default='this is my bio'),
            preserve_default=False,
        ),
    ]
